In [1]:
import tensorflow as tf

In [12]:
x = tf.placeholder(tf.float32,[None,784])

In [13]:
print(x)

Tensor("Placeholder_1:0", shape=(?, 784), dtype=float32)


In [14]:
x_image = tf.reshape(x,[-1,28,28,1])

In [17]:
b_conv1=tf.Variable(tf.constant(0.1,shape=[36]))

In [18]:
print(b_conv1)

<tf.Variable 'Variable:0' shape=(36,) dtype=float32_ref>


In [21]:
sess = tf.Session()
print(sess.run(b_conv1, feed_dict={x: rand_array}))

ValueError: Cannot feed value of shape (3, 3) for Tensor 'Placeholder_1:0', which has shape '(?, 784)'

In [10]:
sess = tf.Session()

In [11]:
print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.70368123  0.21601242  0.30841538]
 [ 0.9226135   0.82411796  0.98223394]
 [ 0.45623234  0.53577125  0.62279272]]
